# coding:utf-8

class PositionOutputer:
    def __init__(self):
        self.datas = list()
    def collect_data(self, position):
        if position is None:
            return
        self.datas.append(position)
    def output_html(self):
        fout = open('positionDetails.html', 'w')
        fout.write("<html>")
        fout.write("<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />")
        fout.write("<body>")
        fout.write("<table>")
        fout.write("<tr>")
        fout.write("<td>职位名称</td>")
        fout.write("<td>工作地区</td>")
        fout.write("<td>学历</td>")
        fout.write("<td>职位描述</td>")
        fout.write("<td>职位人数</td>")
        fout.write("<td>有效起始日期</td>")
        fout.write("<td>有效截止日期</td>")
        fout.write("<td>实习或全职</td>")
        fout.write("<td>薪水</td>")
        fout.write("</tr>")
        for position in self.datas:
            fout.write("<tr>")
            fout.write("<td>%s</td>"%position.name.encode('utf-8'))
            fout.write("<td>%s</td>"%position.city.encode('utf-8'))
            fout.write("<td>%s</td>"%position.degree.encode('utf-8'))
            fout.write("<td>%s</td>"%position.desc.encode('utf-8'))
            fout.write("<td>%s</td>"%position.personNum.encode('utf-8'))
            fout.write("<td>%s</td>"%position.validStartDate.encode('utf-8'))
            fout.write("<td>%s</td>"%position.validEndDate.encode('utf-8'))
            fout.write("<td>%s</td>"%position.requirement.encode('utf-8'))
            fout.write("<td>%s</td><br/>"%position.salary.encode('utf-8'))
            fout.write("\n")
            fout.write("</tr>")
        fout.write("</table>")
        fout.write("</body>")
        fout.write("</html>")
        fout.close()
    def output_txt(self):
        fout = open('positionDetails.txt', 'w')
        fout.write("职位名称\t")
        fout.write("工作地区\t")
        fout.write("学历\t")
        fout.write("职位描述\t")
        fout.write("职位人数\t")
        fout.write("有效起始日期\t")
        fout.write("有效截止日期\t")
        fout.write("实习或全职\t")
        fout.write("薪水\t")
        fout.write("\n")
        for position in self.datas:
            fout.write("%s\t"%position.name.encode('utf-8'))
            fout.write("%s\t"%position.city.encode('utf-8'))
            fout.write("%s\t"%position.degree.encode('utf-8'))
            fout.write("%s\t"%position.desc.encode('utf-8'))
            fout.write("%s\t"%position.personNum.encode('utf-8'))
            fout.write("%s\t"%position.validStartDate.encode('utf-8'))
            fout.write("%s\t"%position.validEndDate.encode('utf-8'))
            fout.write("%s\t"%position.requirement.encode('utf-8'))
            fout.write("%s\t"%position.salary.encode('utf-8'))
            fout.write("\n")
        fout.close()